<?php
$head="head.php";
$header="header.php";
$sidebar="sidebar.php";
$footer="footer.php";
$page=(isset($_GET["page"]))?$_GET["page"]:"welcome";
$title=(isset($_GET["title"]))?$_GET["title"]:"$page";
$content="$page.php";
$apptitle="$title";
require("mypage.php");
?>